### ISSUE TITLE
Cloudflare Workers encountered an error.

### ISSUE THREAD

**Issue by plainsquirrel** [block65/webcrypto-web-push#5]
X [ERROR] Could not resolve "node:crypto"

    node_modules/@block65/webcrypto-web-push/dist/lib/isomorphic-crypto.js:3:13:
      3 │     : import('node:crypto'));
        ╵              ~~~~~~~~~~~~~

  The package "node:crypto" wasn't found on the file system but is built into node. Are you trying
  to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

**Comment by plainsquirrel** [comment]
@maxholman After modifying isomorphic-crypto.js like this, cloudflare workers are built. Any other ideas to fix the error?

```typescript
const impl = await globalThis.crypto;
export const crypto = {
    getRandomValues: (array) => 'webcrypto' in impl
        ? impl.webcrypto.getRandomValues(array)
        : impl.getRandomValues(array),
    subtle: 'webcrypto' in impl ? impl.webcrypto.subtle : impl.subtle,
};
export const CryptoKey = 'webcrypto' in impl ? impl.webcrypto.CryptoKey : globalThis.CryptoKey;
```

**Comment by maxholman** [comment]
@plainsquirrel I just published a stable v1 release to npm - it has some changes that might resolve this problem.  Let me know if it helps.

Also btw this repo now has a full cloudflare worker example

**Comment by plainsquirrel** [comment]
Thank you! @maxholman
